<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37025" started-at="2018-11-19T01:44:00Z" finished-at="2018-11-19T01:44:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37025" started-at="2018-11-19T01:44:00Z" finished-at="2018-11-19T01:44:37Z">
      <class name="com.cs.qa.tests.SignUpPageTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="setUp" is-config="true" duration-ms="15766" started-at="2018-11-19T01:43:45Z" finished-at="2018-11-19T01:44:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test_invalid_uname()[pri:1, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="test_invalid_uname" duration-ms="4374" started-at="2018-11-19T01:44:00Z" finished-at="2018-11-19T01:44:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_invalid_uname -->
        <test-method status="PASS" signature="test_invalid_email()[pri:2, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="test_invalid_email" duration-ms="3664" started-at="2018-11-19T01:44:05Z" finished-at="2018-11-19T01:44:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_invalid_email -->
        <test-method status="PASS" signature="test_invalid_email_username()[pri:3, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="test_invalid_email_username" duration-ms="4012" started-at="2018-11-19T01:44:09Z" finished-at="2018-11-19T01:44:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_invalid_email_username -->
        <test-method status="FAIL" signature="test_invalid_user_1()[pri:3, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="test_invalid_user_1" duration-ms="3997" started-at="2018-11-19T01:44:13Z" finished-at="2018-11-19T01:44:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen] but found [Email is invalid or already taken]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen] but found [Email is invalid or already taken]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.cs.qa.tests.SignUpPageTests.test_invalid_user_1(SignUpPageTests.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_invalid_user_1 -->
        <test-method status="PASS" signature="test_invalid_password()[pri:4, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="test_invalid_password" duration-ms="11440" started-at="2018-11-19T01:44:17Z" finished-at="2018-11-19T01:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_invalid_password -->
        <test-method status="PASS" signature="test_invalid_password_1()[pri:5, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="test_invalid_password_1" duration-ms="9400" started-at="2018-11-19T01:44:28Z" finished-at="2018-11-19T01:44:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_invalid_password_1 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.cs.qa.tests.SignUpPageTests@6a4f787b]" name="TearDown" is-config="true" duration-ms="1480" started-at="2018-11-19T01:44:38Z" finished-at="2018-11-19T01:44:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.cs.qa.tests.SignUpPageTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
