<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FINLHYDAG451278" ignored="0" name="Default test" tests="6" failures="1" timestamp="19 Nov 2018 01:44:38 GMT" time="37.025" errors="0">
  <testcase name="test_invalid_uname" time="4.374" classname="com.cs.qa.tests.SignUpPageTests"/>
  <testcase name="test_invalid_email" time="3.664" classname="com.cs.qa.tests.SignUpPageTests"/>
  <testcase name="test_invalid_email_username" time="4.012" classname="com.cs.qa.tests.SignUpPageTests"/>
  <testcase name="test_invalid_user_1" time="3.997" classname="com.cs.qa.tests.SignUpPageTests">
    <failure type="java.lang.AssertionError" message="expected [Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen] but found [Email is invalid or already taken]">
      <![CDATA[java.lang.AssertionError: expected [Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen] but found [Email is invalid or already taken]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.cs.qa.tests.SignUpPageTests.test_invalid_user_1(SignUpPageTests.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_invalid_user_1 -->
  <testcase name="test_invalid_password" time="11.44" classname="com.cs.qa.tests.SignUpPageTests"/>
  <testcase name="test_invalid_password_1" time="9.4" classname="com.cs.qa.tests.SignUpPageTests"/>
</testsuite> <!-- Default test -->
